#!/usr/bin/env python3
"""Generate topic-wise navigation indexes without moving solution directories."""

from __future__ import annotations

import argparse
import json
import re
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable

REPO_ROOT = Path(__file__).resolve().parents[1]
MAPPING_PATH = REPO_ROOT / "scripts" / "topic-mapping.json"
TOPIC_OUTPUT_DIR = REPO_ROOT / "topic-wise-solution"
ROOT_README_PATH = REPO_ROOT / "README.md"
PROBLEM_DIR_PATTERN = re.compile(r"^(?P<number>\d{4})-(?P<slug>[a-z0-9-]+)$")


@dataclass(frozen=True)
class TopicConfig:
    slug: str
    name: str
    source_dir: str


@dataclass(frozen=True)
class Problem:
    number: str
    title: str
    source_path: Path


def load_topics() -> list[TopicConfig]:
    payload = json.loads(MAPPING_PATH.read_text(encoding="utf-8"))
    topics = [TopicConfig(**topic) for topic in payload["topics"]]
    source_dirs = [topic.source_dir for topic in topics]
    if len(source_dirs) != len(set(source_dirs)):
        raise ValueError("Duplicate source_dir entries found in topic mapping")
    return topics


def title_from_slug(slug: str) -> str:
    return " ".join(part.capitalize() for part in slug.split("-"))


def discover_problems(source_dir: Path) -> list[Problem]:
    problems: list[Problem] = []
    for entry in sorted(source_dir.iterdir(), key=lambda p: p.name):
        if not entry.is_dir():
            continue
        match = PROBLEM_DIR_PATTERN.match(entry.name)
        if not match:
            raise ValueError(f"Unexpected directory in topic source '{source_dir.name}': {entry.name}")
        problems.append(
            Problem(
                number=match.group("number"),
                title=title_from_slug(match.group("slug")),
                source_path=entry,
            )
        )
    return sorted(problems, key=lambda item: (int(item.number), item.title))


def render_topic_page(topic: TopicConfig, problems: list[Problem]) -> str:
    lines = [
        f"# {topic.name}",
        "",
        "_Generated by `scripts/generate_topic_indexes.py`. Do not edit manually._",
        "",
        f"Total problems: **{len(problems)}**",
        "",
        "## Problems",
        "",
    ]
    for problem in problems:
        relative_target = problem.source_path.relative_to(REPO_ROOT)
        lines.append(f"- [{problem.number} - {problem.title}](../{relative_target.as_posix()}/)")
    lines.append("")
    return "\n".join(lines)


def render_topic_index(topic_problem_map: list[tuple[TopicConfig, list[Problem]]]) -> str:
    lines = [
        "# Topic-wise Solution Navigation",
        "",
        "_Generated by `scripts/generate_topic_indexes.py`. Do not edit manually._",
        "",
        "This folder contains topic indexes only. Original problem solutions stay in their existing directories.",
        "",
        "## Topics",
        "",
    ]
    for topic, problems in topic_problem_map:
        lines.append(f"- [{topic.name}](./{topic.slug}.md) ({len(problems)})")
    lines.append("")
    return "\n".join(lines)


def render_root_readme(topic_problem_map: list[tuple[TopicConfig, list[Problem]]]) -> str:
    lines = [
        "# LeetCode DSA Solutions",
        "",
        "This repository keeps all existing solution directories as the single source of truth.",
        "",
        "## Topic-wise Navigation (Generated)",
        "",
        "_Generated by `scripts/generate_topic_indexes.py`. Do not edit this section manually._",
        "",
    ]
    for topic, problems in topic_problem_map:
        lines.append(f"- [{topic.name}](./topic-wise-solution/{topic.slug}.md) ({len(problems)})")

    lines.extend(
        [
            "",
            "## Update the generated indexes",
            "",
            "```bash",
            "python3 scripts/generate_topic_indexes.py",
            "```",
            "",
            "The generator validates topic coverage and link targets while updating README and topic indexes.",
            "",
        ]
    )
    return "\n".join(lines)


def write_or_check(path: Path, content: str, check_only: bool) -> bool:
    existing = path.read_text(encoding="utf-8") if path.exists() else None
    if existing == content:
        return False
    if check_only:
        return True
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    return True


def verify_unique_and_existing(paths: Iterable[Path]) -> None:
    seen: set[Path] = set()
    for path in paths:
        if path in seen:
            raise ValueError(f"Duplicate problem directory mapped multiple times: {path}")
        if not path.exists():
            raise ValueError(f"Missing problem directory in mapping output: {path}")
        seen.add(path)


def verify_link_targets(topic_problem_map: list[tuple[TopicConfig, list[Problem]]]) -> None:
    for topic, problems in topic_problem_map:
        for problem in problems:
            target = problem.source_path
            if not target.exists() or not target.is_dir():
                raise ValueError(f"Broken link target for {topic.name}: {target}")


def discover_source_dirs_with_problems(repo_root: Path) -> set[str]:
    source_dirs: set[str] = set()
    for entry in repo_root.iterdir():
        if not entry.is_dir():
            continue
        for child in entry.iterdir():
            if child.is_dir() and PROBLEM_DIR_PATTERN.match(child.name):
                source_dirs.add(entry.name)
                break
    return source_dirs


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Verify generated files are up to date")
    args = parser.parse_args()

    topics = load_topics()
    topic_problem_map: list[tuple[TopicConfig, list[Problem]]] = []
    configured_source_dirs = {topic.source_dir for topic in topics}
    discovered_source_dirs = discover_source_dirs_with_problems(REPO_ROOT)
    if configured_source_dirs != discovered_source_dirs:
        raise ValueError(
            "Topic mapping does not match discovered problem source directories. "
            f"Configured: {sorted(configured_source_dirs)} | Discovered: {sorted(discovered_source_dirs)}"
        )

    all_problem_paths: list[Path] = []
    for topic in topics:
        source_dir = REPO_ROOT / topic.source_dir
        if not source_dir.exists() or not source_dir.is_dir():
            raise ValueError(f"Configured topic source directory does not exist: {topic.source_dir}")

        problems = discover_problems(source_dir)
        topic_problem_map.append((topic, problems))
        all_problem_paths.extend(problem.source_path for problem in problems)

    verify_unique_and_existing(all_problem_paths)
    verify_link_targets(topic_problem_map)

    changed = False
    changed |= write_or_check(ROOT_README_PATH, render_root_readme(topic_problem_map), args.check)
    changed |= write_or_check(TOPIC_OUTPUT_DIR / "README.md", render_topic_index(topic_problem_map), args.check)

    for topic, problems in topic_problem_map:
        changed |= write_or_check(TOPIC_OUTPUT_DIR / f"{topic.slug}.md", render_topic_page(topic, problems), args.check)

    if args.check and changed:
        print("Generated topic indexes are out of date. Run: python3 scripts/generate_topic_indexes.py")
        return 1

    print("Topic indexes generated successfully.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
